server:
  port: 7002
spring:
  application:
    name: cloud-eureka2-server
eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false # false表示不向eureka中注册  eureka不需要自己注册自己
    fetch-registry: false # false 表示自己就是注册中心，职责就是维护服务实例，不需要检索服务
    service-url:
      defaultZone: http://eureka7001:7001/eureka/  #设置注册地址
