server:
  port: 8802
spring:
  application:
    name: cloud-stream-receive-service
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: 122.51.248.121
                port: 5672
                username: admin
                password: admin
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: heitaoc   #分组同一个组，只有一个消费，并且能消费停机中为消费的信息
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点为所谓，集群必须配置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka #注册地址
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true   #访问路径可以显示ip